// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "lodash", "backbone", "plugins/backbone.layoutmanager"], function($, _, Backbone) {
    var JST, app;
    app = {
      root: "/"
    };
    JST = window.JST = window.JST || {};
    Backbone.LayoutManager.configure({
      manage: true,
      paths: {
        layout: "app/templates/layouts/",
        template: "app/templates/"
      },
      fetch: function(path) {
        var done;
        done = this.async();
        path = path + ".html";
        if (JST[path]) {
          return JST[path];
        }
        return $.ajax({
          url: app.root + path
        }).then(function(contents) {
          return done(JST[path] = _.template(contents));
        });
      }
    });
    return _.extend(app, {
      module: function(additionalProps) {
        return _.extend({
          Views: {}
        }, additionalProps);
      },
      useLayout: function(name) {
        var layout;
        if (this.layout && this.layout.options.template === name) {
          return this.layout;
        }
        if (this.layout) {
          this.layout.remove();
        }
        layout = new Backbone.Layout({
          template: name,
          className: "layout " + name,
          id: "layout"
        });
        $("#main").empty().append(layout.el);
        layout.render();
        this.layout = layout;
        return layout;
      }
    }, Backbone.Events);
  });

}).call(this);
