// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    deps: ["main"],
    paths: {
      libs: "../assets/js/libs",
      plugins: "../assets/js/plugins",
      vendor: "../assets/vendor",
      jquery: "../assets/js/libs/jquery",
      lodash: "../assets/js/libs/lodash",
      backbone: "../assets/js/libs/backbone"
    },
    shim: {
      backbone: {
        deps: ["lodash", "jquery"],
        exports: "Backbone"
      },
      "plugins/backbone.layoutmanager": ["backbone"]
    }
  });

}).call(this);
