// Generated by CoffeeScript 1.3.3
(function() {

  define(["app"], function(app) {
    var Router;
    Router = Backbone.Router.extend({
      routes: {
        "": "index"
      },
      index: function() {
        return window.app = app;
      }
    });
    return Router;
  });

}).call(this);
